name: Tests

on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ['3.9', '3.10', '3.11']
                include:
                    - toxenv: py
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{matrix.python-version}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{matrix.python-version}}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install tox tox-gh-actions
            - name: Test with tox
              run: tox
              env:
                PYTHONPATH: ${{github.workspace}}